### PR TITLE
Cb create post ticket6

### PR DESCRIPTION
**Pull request by CalBoyt**
**Description:**
Trello ticket 6: https://trello.com/c/LxzvXqYu/6-6-create-a-post

This ticket allows the logged in user to create a new post.

**Tasks done for this ticket:**
-  Post Model, Post Repository, IPost Repository, and Post Controller were updated on the server-side to accomplish a successful API POST request to create a post.
- PostForm.js was built and function with fetch call added to PostManager.js on the client-side.
- "/postform" route path added to Application Views as well as linked in the navbar on the client-side.

**Type of change**
- [x] New feature (non-breaking change which adds functionality)

**Testing Instructions**
1. git add and git commit whatever you're working on on your branch.
2. git checkout main.
3. git fetch -a.
4. git checkout my branch: cb-CreatePost-Ticket6.
5. If you don't see the most recent version of my files, git pull origin cb-CreatePost-Ticket6.
6.  (if not already done) Please open the TabloidFullStack.sln with Visual Studio 2022.
7.  (if not already done) **Install your dependencies** by running npm install from the same directory as your package.json fille.
8.  **launch the API** by clicking the execute with debugger solid green button in Visual Studio 2022.
12. Open a new GitBash window and CD into the client folder of the project and **open Visual Studio Code** with the command "code .", then launch the react app with the command "npm start".
13. In the react app, if you are not already logged in, you should be directed to the login page. Please **log in** with this email address: "foo@bar.com". This should redirect you back to the home page.
14. On nav bar, **click "New Post"**. You should be directed to a form to enter the Title, content, category (from drop-down selection), location of your image, and publish date time. Enter test data into each of these fields and click "Submit Post". Verify that you are redirected to the "/post/${post.id}" path for the details of the post, and your that post has been saved with all the information you entered. Please also verify that it displays the author display name for the user you are logged in as, as well as the publication date. 

Checklist:
- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by loganvanmeter — CHANGES_REQUESTED** [review]
1. Menu option should say `New Post` not add post according to the ticket
2. Form does not include an optional field for Publication Date
3. Form does not include required field for category selection
4. Once post is created is does not redirect you to the post details page for that post
5. Post approval should be marked as true for the time being until we get to the later ticket so you can see your post in post details

**Comment by CalBoyt** [comment]
The requested changes have been made.

**Review by MaxAguilar712 — APPROVED** [review]

**Comment by loganvanmeter** [comment]
Cannot make a post without publication datetime. Returns an undefinied error and a 400 badrequest error

**Comment by loganvanmeter** [comment]
Still getting errors when I try to make a post
Caleen'sErrorList

**Comment by loganvanmeter** [comment]
Still receiving the same error. I think it has to do with your post details. You might need to do optional chaining on the post.userProfile.firstName

**Comment by loganvanmeter** [comment]
Still cannot add a post to database without publication date and posts added to database with publication date have a UserTypeId of 0

**Review by NorwoodH — APPROVED** [review]
Tested and working as per instructions!

**Review by loganvanmeter — APPROVED** [review]
Everything looks good

**Pull request merged**
