### PR TITLE
Nh ticket twenty three

### PR DESCRIPTION
**Pull request by NorwoodH**
Trello ticket 23. Admin once logged in is able to see the User Profile link in the navbar, when chosen the admin can see a list of all users. Display name, full name, and user type are displayed in alphabetical order. If logged in user is not an admin, they will not be able to view a list of users.

Checklist

Code has been tested and works on my end following instructions below
Commented code in difficult to understand areas
My changes generate no new warnings or errors
I have added test instructions below that prove my feature implemented and working as intended.

1. git add and git commit whatever you're working on on your branch
2. git checkout main 
3. git fetch --a 
4. git checkout nh-ticket-twenty-three
5. If you don't see the most recent version of my files git pull origin nh-ticket-twenty-three
6. If you have not created the database please do so and follow Steps 7-8 otherwise proceed to Step 9
7. Run this [SQL script](https://github.com/NewForce-Cohort-8/tabloidfullstack-suplex-syndicate/blob/main/SQL/01_Tabloid_Create_DB.sql) to create the initial database
8. Run this [SQL script](https://github.com/NewForce-Cohort-8/tabloidfullstack-suplex-syndicate/blob/main/SQL/02_Tabloid_Seed_Data.sql) to seed the initial data
9. Open the TabloidFullStack.sln with Visual Studio
10. At the top of Visual Studio, select https as the launcher and click the green play button
11. The Swagger UI should appear in the browser
12. Confirm Admin can see User Profiles in navbar and that it works when clicked on and you can see a list of users with display name, full name, and account type in alphabetical order.
13. If the React app isn't already running, in your terminal npm start otherwise refresh the React App.
14. First login as an admin, foo@bar.com. Note any admin login works.
15. Test User Profile link and page.
16. Logout, and login as an author. ecornfoot8@cargocollective.comx is one of the user logins. Note any author login works.
18. Make sure the non admin login you are using cannot navigate to User Profiles.
19. Please leave comment and approve/deny PR.

### CODE REVIEW

**Review by loganvanmeter — CHANGES_REQUESTED** [review]
Can still manually navigate to the route in the url and see User Profiles if not an admin

**Comment by NorwoodH** [comment]
> Can still manually navigate to the route in the url and see User Profiles if not an admin

Issue has now been fixed!

**Review by loganvanmeter — APPROVED** [review]
This works!

**Review by CalBoyt — APPROVED** [review]
Works as described.

**Pull request merged**
